# Generated by Django 4.2.1 on 2023-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='occupation',
            field=models.CharField(default='unspecified', max_length=40),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
